helpdesk_member_knowledgebase_theme:
    path:     /branding/theme/{type}
    controller: Webkul\UVDesk\SupportCenterBundle\Workstation\Branding::theme
    defaults: { panelId: 'themes', type: '' }

helpdesk_member_knowledgebase_spam:
    path:     /block/spam
    controller: Webkul\UVDesk\SupportCenterBundle\Workstation\Branding::spam
    defaults: { panelId: 'settings', type: '' }

helpdesk_member_knowledgebase_update_theme_xhr:
    path:     /branding/ajax
    controller: Webkul\UVDesk\SupportCenterBundle\Workstation\Branding::BrandingXhr
